version: '1.0'
stages:
 - deploy
steps:
    deploy:
        stage: 'deploy'
        image: 'registry.docker.io/mateothegreat/docker-alpine-gcloud-kubectl:latest'
        commands:
            - git submodule update --init
            - kubectl config set-cluster kube-cluster --server="$GCP_K8_API_URL" --insecure-skip-tls-verify=true
            - kubectl config set-credentials cicd --token="$GCP_K8_TOKEN"
            - kubectl config set-context default-context --cluster=kube-cluster --user=cicd
            - kubectl config use-context default-context
            - make install
    