version: '3.7'

services:

  wordpress:

    image: wordpress
    restart: always
    ports: 
      - 80:80
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - mysql

    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    links:
      - mysql

  mysql:
  
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
volumes:
  wordpress-data:
  mysql-data: