apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress:latest
        # - image: wordpress:4.9.4-fpm-alpine
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql            
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DB_USER
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              value: wordpress  
              # valueFrom:
              #   secretKeyRef:
              #     name: mysql-pass
              #     key: password.txt
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: config-volume
              mountPath: /usr/local/etc/php/conf.d/uploads.ini
            - name: wordpress-local-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-local-storage
          persistentVolumeClaim:
            claimName: wordpress
        - name: config-volume
          configMap:
            name: wordpress-config
            items:
            - key: uploads.ini
              path: uploads.ini