apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $SERVICE_NAME-volume
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
