apiVersion: v1
kind: Service
metadata:
  labels:
    app: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  # type: NodePort
  ports:
  - port: 80
    # targetPort: 80
    # name: www
    # protocol: TCP
  selector:
    app: $SERVICE_NAME
